language: objective-c
before_script:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install carthage
- carthage bootstrap --no-use-binaries
xcode_project: kawa.xcodeproj
xcode_scheme: kawa
osx_image: xcode7.3
script:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: G0W8iO8MzorTJioszmTDKxOtWZPAN86Yc9BrmbbJ146JSSE2H3+HBjG8kPXJL5mEJy+D3T87jeGZ9F0aRXK8BfnjirlO0720W3ZZAh/2JLGeRnvz4yG+uGQsw37ZxhoclyRs6p3im7rEURI5BfnDF6b2Bdsl7oOtvnwV9tfoNvrttHKXJBqK+uETvUk3YlPqRyKFHdx45AoXtuMqtJq4S9mqatT6RxycgP+X/UweHjKH4h9zfNlWvN3iQCpcTOruPVw8KpRXhS4snBLSB8/vVrnay+Y2qRLy9AwfL6XvqJefQKw2oFBFXEZfwzgRQJp4Be/PmuIaXFmy8aX+XKWMwmcj17EmtPFq5cZAsB2PdBz2VRhyZclPovDnFSpfW4aVs0Z4ogkNY1L0X7M/g4Y31ZSjtWY4Yh4V6zhnj7odnrDAV4pkw8wkmmQNvQxFp0qq2xdhLFKIDZapBTbkpsAVEhibg2UoOItW/ftQ1gBGA48tmv7fN7ttjR+tNK4PRW1KpchpKzFcVyTAPyoZEp8/ViCb8TWu+F0eRefPff8RGiufBVfGZTM0MLviaHwxQV/eCKOYKV4ZeZoaBX39jycoRi5p9G4ksh3jVPGoRA5UmyEC7NbszJtopbWQd4AYtWADQBEOE9XkjMFsCAx8NtvVKDfrRB3epBaKqE6qLV+J/s0=
  file: Kawa.zip
  clean_up: false
  skip_cleanup: true
  on:
    repo: noraesae/kawa
    all_branches: true
    tags: true
before_deploy:
- git fetch --tags
- zip -r Kawa Kawa.app
